### ISSUE TITLE
BioProject accession for PBMC faulty?

### ISSUE THREAD

**Issue by kloot** [WEHIGenomicsRnD/Manuscript_Sample-Multiplexing-Oligo-Comparison#1]
Hi,

Could you please verify the BioProject accession for the PBMC data.
NCBI returns 'not found' for `PRJNA106402`
Thanks in advance!

**Comment by dvbrown** [comment]
Thank you for bringing it to my attention. Must be a copy paste or transcription error from me.
ID is PRJNA1064602
https://www.ncbi.nlm.nih.gov/bioproject/PRJNA1064602
